/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posten: Posten;
    kaufanfragen: Kaufanfragen;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posten: PostenSelect<false> | PostenSelect<true>;
    kaufanfragen: KaufanfragenSelect<false> | KaufanfragenSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posten".
 */
export interface Posten {
  id: number;
  titel: string;
  beschreibung?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  kategorie:
    | 'smartphones'
    | 'maschinen'
    | 'fahrzeuge'
    | 'it-bueroelektronik'
    | 'sonstiges'
    | 'gastronomie'
    | 'moebel-einrichtung'
    | 'energie-gebaeudetechnik'
    | 'lager-logistik-reinigung';
  /**
   * Preis in Euro. Leer lassen, wenn "Preis auf Anfrage" aktiv ist.
   */
  preis?: number | null;
  preisAufAnfrage?: boolean | null;
  status: 'verfuegbar' | 'reserviert' | 'verkauft';
  bilder?: (number | Media)[] | null;
  /**
   * z.B. Aktenzeichen oder Bezeichnung des Verfahrens
   */
  insolvenzverfahren?: string | null;
  zustand: 'neu' | 'gebraucht' | 'restbestand';
  /**
   * Ein Satz für die Kartenansicht, z.B. "45 MP Vollformat, 8K RAW Video"
   */
  kurzspezifikation?: string | null;
  /**
   * Verfügbare Menge dieser Position
   */
  stueckzahl: number;
  standort?: string | null;
  /**
   * z.B. Gutachten, Datenblätter, Zustandsprotokolle
   */
  dokumente?: (number | Media)[] | null;
  /**
   * Nur aktivierte Posten werden auf der öffentlichen Seite angezeigt.
   */
  veroeffentlicht?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingehende Sofortkauf-Anfragen aus dem öffentlichen Katalog.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kaufanfragen".
 */
export interface Kaufanfragen {
  id: number;
  produkt: number | Posten;
  /**
   * Schnappschuss des Produkttitels zum Zeitpunkt der Anfrage.
   */
  produktTitel: string;
  produktKategorie?: string | null;
  produktStandort?: string | null;
  /**
   * Server-seitig geprüfter Preis zum Zeitpunkt der Anfrage. Leer = Preis auf Anfrage.
   */
  preis?: number | null;
  kaeuferTyp: 'privatperson' | 'unternehmen';
  vorname: string;
  nachname: string;
  email: string;
  telefon: string;
  adresse: {
    strasse: string;
    hausnummer: string;
    plz: string;
    ort: string;
    land: string;
  };
  /**
   * Optionale, allgemeine Firmenangabe (unabhängig vom Käufertyp).
   */
  firma?: string | null;
  /**
   * Nur bei Käufertyp "Unternehmen / Gewerbe".
   */
  firmenname?: string | null;
  handelsregisternummer?: string | null;
  ustIdNr?: string | null;
  /**
   * Nur die Bezeichnung der eingereichten Dokumente zur Nachverfolgung. Die eigentlichen Dateien wurden ausschließlich per E-Mail an DPSS Management gesendet und nirgends gespeichert.
   */
  eingereichteDokumente?:
    | {
        bezeichnung: string;
        dateiname: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Die Dokumente selbst liegen nur als E-Mail-Anhang bei DPSS Management vor, nicht im Admin.
   */
  identifikationsstatus: 'eingegangen' | 'unvollstaendig' | 'geprueft';
  status: 'neu' | 'identifikation_ausstehend' | 'geprueft' | 'abgelehnt' | 'abgeschlossen';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posten';
        value: number | Posten;
      } | null)
    | ({
        relationTo: 'kaufanfragen';
        value: number | Kaufanfragen;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posten_select".
 */
export interface PostenSelect<T extends boolean = true> {
  titel?: T;
  beschreibung?: T;
  kategorie?: T;
  preis?: T;
  preisAufAnfrage?: T;
  status?: T;
  bilder?: T;
  insolvenzverfahren?: T;
  zustand?: T;
  kurzspezifikation?: T;
  stueckzahl?: T;
  standort?: T;
  dokumente?: T;
  veroeffentlicht?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kaufanfragen_select".
 */
export interface KaufanfragenSelect<T extends boolean = true> {
  produkt?: T;
  produktTitel?: T;
  produktKategorie?: T;
  produktStandort?: T;
  preis?: T;
  kaeuferTyp?: T;
  vorname?: T;
  nachname?: T;
  email?: T;
  telefon?: T;
  adresse?:
    | T
    | {
        strasse?: T;
        hausnummer?: T;
        plz?: T;
        ort?: T;
        land?: T;
      };
  firma?: T;
  firmenname?: T;
  handelsregisternummer?: T;
  ustIdNr?: T;
  eingereichteDokumente?:
    | T
    | {
        bezeichnung?: T;
        dateiname?: T;
        id?: T;
      };
  identifikationsstatus?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}